input:
  http_server:
    address: ""
    path: /post
    ws_path: /post/ws
    timeout: 5s
    rate_limit: ""

pipeline:
  processors:
  - json:
      operator: copy
      path: content
      value: sarcasm
  - process_field:
      path: sarcasm
      processors:
      - type: how_sarcastic
